services:
  postgres:
    image: postgres:16
    container_name: shelfwise_postgres
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: shelfwise_app
    restart: always
    environment:
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_PORT: ${DB_PORT}
      APP_PORT: ${APP_PORT}
      DB_HOST: postgres
    ports:
      - "3000:${APP_PORT}"
    depends_on:
      - postgres
    command: npm start

volumes:
  postgres_data:
